filebeat.inputs:
  - type: filestream
    id: cvsfiles
    paths:
      - /data/input/*.csv
    close_eof: true
    clean_removed: true

output.kafka:
  hosts: ["redpanda:9092"]
  topic: 'input'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

processors:
  - drop_fields:
      fields: ["host", "agent", "ecs", "log", "input", "cloud", "event", "value", "@metadata", "@timestamp"]

setup.template.enabled: false
setup.ilm.enabled: false

